sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "WljQOYULW8nFJMJP8VTbB4hyt9auMWAH7fw5JiyypGjWGL82CUnGf8iHP5gJrLdzARxGFT9I7L9JhKmRmBTn81mc9zw4wRX29QXZ2FkG9NjLpN1CGYfy0oiiDvdkeuG4uMD70S1+qqJEyYBYqRfcdGxzhb5C89nvVRc/Ah7dBVTxbt47m0ZhX/jZdrgh6TBn4uduRbjnqKWY9Zc3M/JlboSyl2UUgVHqLibQ5z3ZYdMqC8uKGk3V7ELd8yz1l5AVNXGM6BKvogkKQLHiZv5PwhLzmUPEcyAJXODvuxTL1ZMP1ZuZY1E8VmmKHaofIGUklqwZTr7LIIGjjUH/UfjX9oCDSzceSTZeM1bK4YP6TFNGcMuDncKK1gW6UeBEn82p2nK7Q0TbqrvGAWiG/4I6aUpYL3kEtyGTj28yvcg6+y+K7EoZh4mdxHTWnhmAvMJxzQKL//APAiVWaerDiYLgA6gnNJlBTyHRVORSv9ff8ukOVGWx/dvk2wTGzOpGYLx3HFo7zAUCHIs9NMzRrQ3WgagWuBMaAvDD7Ul3eOGb1CUUaPD4EiwPN/u33oFhYVfY8w/sDZ6ec4FIdF3/dw2mcBRKwJOGhSWe3e9tq5vpqEuHOxHbrguImpB7s7M/nAcFqsVbVmgLGlAFLw74hRFGgleAW1hDZls27yJ3s4KSDbk="
  - secure: "Xb13QCSVXO4RMAbO5raENUknx9WvLj7RBOoI8I6JUynZCZOftgkMkmCN3Of1yWHwENwCNgsIpaI+eFK7dNbyiUY54lsjLEN2K7/tuXOCv/jfod4qC8pci3NNQCk55WGbgZaJqTUMMxMsAl4TYL5VG0eX+ypQL8QPI83j8EkOPhxK5HigpD0o+t4owuVjKSm/xIDVTpultH7PTtw2Zh9E2ZDdD+MufD+XRfcVBlBDTk0XY8ngO2ucXMz+Ep5eAXhe98ieL48B8lSIOYTr4SHAdiYrMiZmvKa7NKF7vChWyOe2xQR3iHsQ88qBWSqtm2BdAgkxz5AsQjUXh21anPBKbxKDIGd2mCDPX4XOW0N5L7UyHbaUpp9e8CLN7IpDy51WBQ4Ht9MNx2uFpatMCrBDMx2xBZiJcP22YHfpA98uTHfPEMvuu01DqT2gMlo6H25CGH6AvCrpUp2F7AkyvVYQSfFV0IYX+dnjLj2eoJeAv3dBGrAXfhO+iv7U4X+Lu8vcmMoOO01BNID93orAXl5vnNeRRCaXbHDr8cMHU5pqrpAsxjGzQ6fv1Lwh2J8ln+3JMnz1PGSM5Z+hrLbbdhhMWUWUtdKkNQydEyVrPT0rzCEIy7CzKltd+1AVmyLuQmhomXRS+Xq1TQMrUAESi4gfpFR1uGNawWfRY94WGSBxuHg="
  - secure: "M3+2xG6pQFVpGOtklEjSU5b9ks+6hKfXxnR7cCwki1qMmhS4Vu0+FN36x3PxcmXscqBOWu9I1AC2k/Cbqnl9F6wGJIufC7otP6tkq19hkZn9owCm1wvyatW8Kgurk+zMNk2ZmcmE4+cqceoUJNPICOrqhKBtGceZjBflWYWPHhcyyLxsIvoYHT4y9o8qAGo0nknBUUEWZMGnWnW3nTuFcpo+PLnC8RVnCOjO0AccuUraMcE5rw3lBZhZjEs3f175c5O9Fqn4NboNqI/Wy9cjBHyQ8rW6iW1wv06eV75NyDcaacNWsCSOOpAGtQs7zbqxdnMBq0jvCxXK+pJtOeYytu5id43w9Ol+YmCFSHVijdeWKmY9EqIwRCoPgCbrYoR21cgCuJN2WN3aCtAd+w+dfLUYZ2eoYnvbeuFd9kIqaixVAPOqMZUgRiaNTvAgxx3bH7JJNR6otgZrH+haCjasGda/vcEjG1TM5FjpxTnwQEnWBzy8eCnW9yMsfmN3TP4doPyssuqNiog68IUuESOl5ge06ikZPiBZWThRGNBkieg5SUZw9Xi87yqTQF5atFt+SwAVqJhj731C3VZHtonwB/dQa3rJSUT2d/0Qtbmc+BLNKZjYt9m1nse4pyK5MaYP1j3QBll7RFHHZun7S0qsUucIBxXpzBrnTE0f5g/96us="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
